name: Play the Game
on: 
  issues:
    types: [opened]
jobs:
  playGame:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Calculate Event ID Line
        run: |
          LINE=$(echo "$EVENT_ID % $(wc -l < words.txt) + 1" | bc)
          echo "Calculated LINE: $LINE"
        env:
          EVENT_ID: ${{ github.event.issue.id }}
      - name: Get the Target Word
        run: |
          TARGET=$(sed -n "${LINE}p" words.txt)
          GUESS=$(echo "$TITLE" | cut -d' ' -f1)
          echo "Target Word: $TARGET"
          echo "Guess: $GUESS"
        env:
          TITLE: ${{ github.event.issue.title }}

